version: "3"
services:
  postgresdb:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: go_simple_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgresdb:5432/go_simple_bank?sslmode=disable
    depends_on:
      - postgresdb
    entrypoint: ["/app/wait-for.sh", "postgresssrv:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    
    



    