version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: go_simple_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/go_simple_bank?sslmode=disable
  #   depends_on:
  #     - postgres
  #   entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
  #   command: ["/app/main"]
    
    



    