
version: "3"

services:
  postgresdb:
    image: postgres
    # restart: always
    environment:
      POSTGRES_DB: go_simple_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata:/var/lib/postgressql/pgdata
    networks:
      - app-tier
    ports:
      - 5432:5432


volumes:
  postgresdata:

networks:
  app-tier:
    driver: bridge
    