name: ci-test

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: go_simple_bank
        options: >-
          --health-cmd ps_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go
    
    - name: Check out code in the Go module directory
      uses: actions/checkout@v2
    
    - name: Test
      run: make test